name: popsycle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - astropy
  - scipy
  - numpy<2.3
  - matplotlib
  - pandas
  - synphot
  - speclite
  - astroquery
  - numba
  - pip:
    - isochrones